services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nexuspay
      POSTGRES_PASSWORD: nexuspay
      POSTGRES_MULTIPLE_DATABASES: nexuspay_auth,nexuspay_payments,nexuspay_notifications
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init-multi-db.sh:/docker-entrypoint-initdb.d/init-multi-db.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexuspay"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: nexuspay
      RABBITMQ_DEFAULT_PASS: nexuspay
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10

  auth-service:
    build: ./services/auth-service
    env_file: ./.env
    environment:
      PORT: 4001
      DATABASE_URL: postgresql://nexuspay:nexuspay@postgres:5432/nexuspay_auth?schema=public
      REDIS_URL: redis://redis:6379
      OTEL_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
    ports:
      - "4001:4001"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4001/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  payments-service:
    build: ./services/payments-service
    env_file: ./.env
    environment:
      PORT: 4002
      DATABASE_URL: postgresql://nexuspay:nexuspay@postgres:5432/nexuspay_payments?schema=public
      REDIS_URL: redis://redis:6379
      OTEL_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
    ports:
      - "4002:4002"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4002/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  notifications-service:
    build: ./services/notifications-service
    env_file: ./.env
    environment:
      PORT: 4003
      DATABASE_URL: postgresql://nexuspay:nexuspay@postgres:5432/nexuspay_notifications?schema=public
      RABBITMQ_URL: amqp://nexuspay:nexuspay@rabbitmq:5672
      OTEL_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
    ports:
      - "4003:4003"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4003/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  api-gateway:
    build: ./services/api-gateway
    env_file: ./.env
    environment:
      PORT: 4000
      REDIS_URL: redis://redis:6379
      AUTH_SERVICE_URL: http://auth-service:4001
      PAYMENTS_SERVICE_URL: http://payments-service:4002
      NOTIFICATIONS_SERVICE_URL: http://notifications-service:4003
      OTEL_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
    ports:
      - "4000:4000"
    depends_on:
      auth-service:
        condition: service_healthy
      payments-service:
        condition: service_healthy
      notifications-service:
        condition: service_healthy
      redis:
        condition: service_healthy

  prometheus:
      image: prom/prometheus:v3.14.0
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
      volumes:
        - ./infra/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        - promdata:/prometheus
      ports:
        - "9090:9090"

  grafana:
    image: grafana/grafana:12.3.11
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./infra/monitoring/grafana/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./infra/monitoring/grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./infra/monitoring/grafana/dashboards/nexuspay-service.json:/var/lib/grafana/dashboards/nexuspay-service.json:ro
      - grafanadata:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      METRICS_STORAGE_TYPE: prometheus
      PROMETHEUS_SERVER_URL: http://prometheus:9090
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:3.5.0
    command:
      - "-config.file=/etc/loki/loki-config.yaml"
    volumes:
      - ./infra/monitoring/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - lokidata:/loki
    ports:
      - "3100:3100"

volumes:
  pgdata:
  redisdata:
  rabbitmqdata:
  promdata:
  grafanadata:
  lokidata:
